language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      env: 
        - BADGE=linux
        - QT_CI_PACKAGES=qt.qt5.5132.gcc_64,qt.qt5.5132.qtwebengine PATH="$TRAVIS_BUILD_DIR/Qt/5.13.2/gcc_64/bin:${PATH}"
      addons:
        apt:
          packages:
            - libxkbcommon-x11-0
            - libgl1-mesa-dev
      services:
        - xvfb

before_install:
  - if [ "$BADGE" = "linux" ]; then
      sudo apt-get update;
    fi

install:
  - if [ "$BADGE" = "linux" ]; then    
      sudo apt-get install libgl-dev python3.6;
      git clone https://github.com/benlau/qtci.git;
      source qtci/path.env;
      install-qt 5.13.2;
      sudo wget https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz;
      sudo tar -xvf go1.13.1.linux-amd64.tar.gz;
      sudo mv go /usr/local;
      export GOROOT=/usr/local/go;
      export PATH=$GOPATH/bin:$GOROOT/bin:$PATH;
    fi

before_script:
  - if [ "$BADGE" = "osx" ];   then    export PATH="/usr/local/Cellar/qt/5.13.1/bin:$PATH"; fi

script:
  - git submodule update --init
  - python3 install_dependency.py
  - cd clashr && python3 build_clashr.py
  - cd ..
  - mkdir build && cd ./build
  - if [ "$BADGE" = "linux" ]; then
      wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage";
      chmod a+x linuxdeployqt-continuous-x86_64.AppImage;
      qmake CONFIG+=release .. PREFIX=/usr;
      make -j$(nproc);
      make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/;
      ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage;
    fi

defore_deploy:
  - cd ..
  - python3 release.py

deploy:
  provider: release
  file: build\ShdowClash-windows.zip
  api_key: $GIT_REPO_TOKEN
  skip_cleanup: true
  overwrite: true
  on:
    branch: master
    tags: true
